name: Android CI (APK)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Use repo secret GEMINI_API_KEY (Settings → Secrets and variables → Actions)
      - name: Create local.properties
        run: |
          echo "sdk.dir=$GITHUB_WORKSPACE/android-sdk" > local.properties
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> local.properties

      - name: Install Android SDK cmdline-tools
        env:
          ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Set up Gradle 8.7
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
          cache-disabled: true

      - name: Make gradlew executable (if present)
        run: if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Build Debug APK
        run: |
          if [ -x ./gradlew ]; then
            ./gradlew clean :app:assembleDebug --no-daemon --stacktrace
          else
            gradle clean :app:assembleDebug --no-daemon --stacktrace
          fi

      - name: List any APKs found
        run: |
          echo "== any *.apk found =="
          find . -type f -name "*.apk" -print || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            app/build/outputs/apk/debug/*.apk
            **/build/outputs/apk/debug/*.apk
          if-no-files-found: error
